model: &std_gpt2
    type: gpt2
    n_positions: 101
    n_layer: 3
    n_embd: 64
    n_head: 2

train:
    optim:
        type: adam
        lr: 0.0001
    loss_fn:
        type: squared
    function_class: 
        type: linear regression
    b_size: 32
    seq_len: !curriculum
        start: 11
        stop: 42
        step_size: 2
        step_len: 5000
    x_dim: !curriculum
        start: 5
        stop: 20
        step_size: 1
        step_len: 10000
    x_dist:
        type: normal
    steps: 500000
    model: *std_gpt2
    baseline_models: []